WebApp-AspNetMVC/APBDProject/Models/Album.cs
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace APBDProject.Models;

public class Album
{
    public int IdAlbum { get; set; }
    public string Title { get; set; }
    public DateTime ReleaseYear { get; set; }
    public virtual ICollection<Song> Songs { get; set; }
    
    
}

WebApp-AspNetMVC/APBDProject/Models/DTO/DTOAlbum.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace APBDProject.Models;

public class DTOAlbum
{
    [Key]
    public int IdAlbum { get; set; }
    
    [Required]
    [MaxLength(100)]
    [DisplayName("Title")]
    public string Title { get; set; }
    
}

WebApp-AspNetMVC/APBDProject/Models/DTO/DTOSong.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace APBDProject.Models;

public class DTOSong
{
    [Key]
    public int IdSong { get; set; }
    
    [Required]
    [MaxLength(100)]
    [DisplayName("Title")]
    public string Title { get; set; }

    [Required]
    [MaxLength(100)]
    [DisplayName("Author")]
    public string Author { get; set; }

    [Required]
    [DisplayName("Duration")]
    public double Duration { get; set; }
    
}

WebApp-AspNetMVC/APBDProject/Models/ErrorViewModel.cs
namespace APBDProject.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp-AspNetMVC/APBDProject/Models/Song.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace APBDProject.Models;

public class Song
{
    public int IdSong { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public double Duration { get; set; }
    public int IdAlbum { get; set; }
    public virtual Album Album { get; set; }
    
}

WebApp-AspNetMVC/APBDProject/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using APBDProject.Models;

namespace APBDProject.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebApp-AspNetMVC/APBDProject/Controllers/SongsController.cs
using APBDProject.Models;
using APBDProject.Repositories;
using APBDProject.Services;
using Microsoft.AspNetCore.Mvc;

namespace APBDProject.Controllers;

public class SongsController : Controller
{
    private ISongsService _songsService;
    
    public SongsController(ISongsService songsService)
    {
        _songsService=songsService;
    }
    
    
    // GET
    public async Task<IActionResult> Index(string query, CancellationToken cancellationToken)
    {
        return View(await _songsService.GetSong(query, cancellationToken));
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    // [HttpPost]
    // public IActionResult Create(Song newStudent)
    // {
    //     if (ModelState.IsValid)
    //     {
    //         songs.Add(newStudent);
    //         return RedirectToAction("Index");
    //     }
    //     
    //     return View(newStudent);
    // }
}

WebApp-AspNetMVC/APBDProject/Views/Home/Index.cshtml
<head>
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true"/>
</head>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 welcome">Welcome</h1>
    <h4>On this site you can find songs or add new ones</h4>
</div>

WebApp-AspNetMVC/APBDProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>SONG BASEMENT- @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/APBDProject.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-custom navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
        <div class="container-fluid" >
            <a class="navbar-custom-brand" asp-area="" asp-controller="Home" asp-action="Index">Song Basement</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="navbar-custom-link" asp-area="" asp-controller="Songs" asp-action="Index">Songs</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer">
    <div class="container">
        &copy; 2024 - Song Basement - <a class="policy" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src ="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp-AspNetMVC/APBDProject/Views/Songs/Create.cshtml
@model Song
<h1>Add new song</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title"/>
        <span asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Author"></label>
        <input class="form-control" asp-for="Author"/>
        <span asp-validation-for="Author"></span>
    </div>
    <div class="form-group">
        <label asp-for="Duration"></label>
        <input class="form-control" asp-for="Duration"/>
        <span asp-validation-for="Duration"></span>
    </div>
    <input type="submit" value="Add"/>
</form>

WebApp-AspNetMVC/APBDProject/Views/Songs/Index.cshtml
<head>
    <link rel="stylesheet" href="~/css/songs.css" asp-append-version="true"/>
</head>

@{
    ViewData["Title"] = "Songs";
}
@model List<Song>
<h1 class="title">All Songs</h1>

    <form method="get" class="form">
        <input type="text" class ="searchInp" name="query" id="query" />
        <button type="submit" class="formBut">Search</button>
        <button type="submit" class="formBut" asp-area="" asp-controller="Songs" asp-action="Create">Add new</button>
    </form>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Duration</th>
    </tr>
    <tr>
    @foreach (var st in Model)
    {
        <tr>
            <td>@st.Title</td>
            <td>@st.Author</td>
            <td>@st.Duration</td>
        </tr>
    }
</table>